### ISSUE TITLE
'Content_loss' object is not iterable

### ISSUE THREAD

**Issue by smilethensee** [JaimeTang/book-code#8]
第八章风格迁移运行的时候出现这个错误，请问该怎么解决呢？？
Traceback (most recent call last):
  File "C:/Users/lucifer/pytorch11/chapter_8.py", line 142, in <module>
    optimizer.step(closure)
  File "C:\Users\3057\.conda\envs\pytorch11\lib\site-packages\torch\optim\lbfgs.py", line 103, in step
    orig_loss = closure()
  File "C:/Users/lucifer/pytorch11/chapter_8.py", line 133, in closure
    for cl in content_loss:
TypeError: 'Content_loss' object is not iterable

Process finished with exit code 1

**Comment by smilethensee** [comment]
for cl in content_losses:
            content_score += cl.backward()
我这里将loss写成了losses,抱歉

**Comment by smilethensee** [comment]
将losses写成了loss，抱歉
